### ISSUE TITLE
The value of theta is different from the paper

### ISSUE THREAD

**Issue by ZiangYan** [Jianbo-Lab/HSJA#1]
Hi Jianbo,

Thanks for your nice work, and it's experimental results are really impressive.

I notice the values of theta are actually different in paper and source code. From equation 17 in the paper, theta should be 0.001 * d^{-3/2} under the l2 constriant. However, in the source code, theta is set to 1 * d^{-3/2} in [this newer commit](https://github.com/Jianbo-Lab/HSJA/blob/6eee9df34d4a3fb9627ffe0c772bfabe172abeec/hsja.py#L69-L72) or 0.01 * d^{-1/2} in [this older commit](https://github.com/Jianbo-Lab/HSJA/blob/ce40aac1f25812fa88247b4d83ef35d12244cf02/bapp.py#L67-L70)

**Comment by Jianbo-Lab** [comment]
Hi @ZiangYan,

Thanks for the catch! That is a typo in my paper. 

Initially theta = 0.01 * d^{-1/2} was used for all the experiments. In the current version of the preprint, we added an improved version of Theorem 2, which explicitly suggests the choice of delta as a function of d. Thus, we redefine theta = 1 * d^{-3/2}.

However, somehow I forgot to change 0.001 to 1. **Please use the choice of theta in the new commit as the default one.** I will update theta in the future version of preprint.

**Comment by ZiangYan** [comment]
Thanks @Jianbo-Lab !

This really clarifies and helps me a lot.
