### ISSUE TITLE
Is it possible and easy to enable batch processing?

### ISSUE THREAD

**Issue by Shawn-Shan** [Jianbo-Lab/HSJA#4]
Hey, 

Really nice work and well written code as well. I would like to ask whether batch processing (optimize several images at the same time) is possible to implement on top of the code base, and whether it will be supported in the future. If not, is there any suggestions on trying to implement batch mode myself. 

Thanks!

**Comment by Jianbo-Lab** [comment]
Hi @Shawn-Shan,

Currently I do not plan to support batch mode for HSJA. It is difficult to implement batch mode, and it may not be worth the efforts (if not for large-scale real-world usage). I will describe the things to note below.

Three main steps in HSJA involve the function evaluation: binary search along a line, gradient estimate and geometric progression (See Figure 2 of https://arxiv.org/pdf/1904.02144.pdf). In the current version, gradient estimate is already calculated in batch (that means multiple perturbed images are evaluated simultaneously). Only binary search and geometric progression involve single-image processing. The main difficulty here is synchronously doing binary search. Different images may end at different steps in binary search. The same applies to geometric progression. A naive implementation will ends with the worst-case efficiency in a batch.

The only way that will improve the efficiency is asynchronous attack, which involves much more work in implementation.

**Comment by Shawn-Shan** [comment]
I see, that makes a lot of sense. Thanks!
