### ISSUE TITLE
How is input norm calculated? 

### ISSUE THREAD

**Issue by Shawn-Shan** [Jianbo-Lab/HSJA#5]
I have a quick question about input norm calculation. I think the linf norm is just the max difference on input space and previous attack works mostly use 0.05 or 8/255. In our paper, the linf norm is really different between ImageNet/CIFAR100 and MNIST/CIFAR10, is that because you calculate the norm on [0,255] space for ImageNet/CIFAR100?

**Comment by Jianbo-Lab** [comment]
Pretty sure mnist, cifar10 and cifar100 use the same norm. For targeted attack, cifar100 can be more difficult as it has more classes.

**Comment by Shawn-Shan** [comment]
Cool, thanks for the clarification.
