### ISSUE TITLE
Which stepsize_search performs better in terms of query and distortion?

### ISSUE THREAD

**Issue by machanic** [Jianbo-Lab/HSJA#6]
Your code has two options for `stepsize_search`: `geometric_progression` and `grid_search`, **which one should I use** for the experiments for the best performance in terms of query and distortion?

**Comment by Jianbo-Lab** [comment]
Different data and models could have different optimal options. 
Geometric progression is the preferred one across experiments for its simplicity. If you aim at the optimal performance, try both.
