### ISSUE TITLE
Why the perturbed image is not clip with min=0 and max=1 after binary search step? Bug?

### ISSUE THREAD

**Issue by machanic** [Jianbo-Lab/HSJA#7]
I notice the statement `perturbed = clip_image(perturbed + epsilon * update,  clip_min, clip_max)` is placed before `perturbed,dist_post_update = binary_search_batch(sample,  perturbed[None], model, params)` in line 110~line 114 (geometric_progression). (https://github.com/Jianbo-Lab/HSJA/blob/master/hsja.py#L114)
Why there is no clipping operation after `perturbed,dist_post_update = binary_search_batch(sample,  perturbed[None], model, params)` ? Is it a bug?

**Comment by Jianbo-Lab** [comment]
No not a bug. Binary search will never exceed the boundary as long as the initial two images do not, by the definition of binary search.
