### ISSUE TITLE
Question about L_infinity norm attack of HSJA.

### ISSUE THREAD

**Issue by machanic** [Jianbo-Lab/HSJA#8]
I read your code carefully, and I have the following questions that confuse me in L-infinity norm of HSJA.

1.  In line : https://github.com/Jianbo-Lab/HSJA/blob/master/hsja.py#L225 why you set `highs = dists_post_update` rather than `highs = np.ones(len(perturbed_images))` used in L2 norm? And also the `thresholds = np.minimum(dists_post_update * params['theta'], params['theta'])` is different from L2 norm version?

2. In function `def project`, why you use the following code to project the `alpha`?  The L2 norm is easier to understand which `return (1-alphas) * original_image + alphas * perturbed_images`  as the middle point lies in the line between `original_image` and `perturbed_images`. How to understand the following L-inf norm code?
```
elif params['constraint'] == 'linf':
		out_images = clip_image(
			perturbed_images, 
			original_image - alphas, 
			original_image + alphas
			)
		return out_images
```

3. Why you use `update = np.sign(gradf)` as the gradient direction in L-infinity norm version? (https://github.com/Jianbo-Lab/HSJA/blob/6a9145643f342b62790712ef1917de14276a200a/hsja.py#L99)

4. Furthermore, is the `gradf` returned by `def approximate_gradient` the same vector as the normal vector of the decision hyperplane?

**Comment by Jianbo-Lab** [comment]
1. It is a better upper bound in the case of L infinity norm than an all-one vector.
2. This is the mathematical definition of orthogonal projection onto an L infinity ball.
3. This is more of intuition and empirical performance. Using sign gradient performs better empirically. The idea can refer to fast gradient sign method. I think there exists literature explaining this from a theoretical viewpoint. 
4. The gradient direction is the normal vector of decision surface. It returns an approximation of that.
